/**
 * Definitions of DMAP tags used by various applications.
 */

import { createDmapTag, type DmapTag } from "./parser.js";
import {
	readBool,
	readBplist,
	readBytes,
	readIgnore,
	readStr,
	readUint,
} from "./tags.js";

function readUnknown(
	_data: Buffer,
	_start: number,
	_length: number,
): undefined {
	return undefined;
}

export const _TAGS: Record<string, DmapTag> = {
	aelb: createDmapTag(readBool, "com.apple.itunes.like-button"),
	aels: createDmapTag(readUint, "com.apple.itunes.liked-state"),
	aeFP: createDmapTag(readUint, "com.apple.itunes.req-fplay"),
	aeGs: createDmapTag(readBool, "com.apple.itunes.can-be-genius-seed"),
	aeSV: createDmapTag(readUint, "com.apple.itunes.music-sharing-version"),
	apro: createDmapTag(readUint, "daap.protocolversion"),
	asai: createDmapTag(readUint, "daap.songalbumid"),
	asal: createDmapTag(readStr, "daap.songalbum"),
	asar: createDmapTag(readStr, "daap.songartist"),
	asgr: createDmapTag(readUint, "com.apple.itunes.gapless-resy"),
	astm: createDmapTag(readUint, "daap.songtime"),
	ated: createDmapTag(readBool, "daap.supportsextradata"),
	caar: createDmapTag(readUint, "dacp.albumrepeat"),
	caas: createDmapTag(readUint, "dacp.albumshuffle"),
	caci: createDmapTag("container", "dacp.controlint"),
	cafe: createDmapTag(readBool, "dacp.fullscreenenabled"),
	cafs: createDmapTag(readUint, "dacp.fullscreen"),
	cana: createDmapTag(readStr, "daap.nowplayingartist"),
	cang: createDmapTag(readStr, "dacp.nowplayinggenre"),
	canl: createDmapTag(readStr, "daap.nowplayingalbum"),
	cann: createDmapTag(readStr, "daap.nowplayingtrack"),
	canp: createDmapTag(readBytes, "daap.nowplayingid"),
	cant: createDmapTag(readUint, "dacp.remainingtime"),
	capr: createDmapTag(readUint, "dacp.protocolversion"),
	caps: createDmapTag(readUint, "dacp.playstatus"),
	carp: createDmapTag(readUint, "dacp.repeatstate"),
	cash: createDmapTag(readUint, "dacp.shufflestate"),
	cast: createDmapTag(readUint, "dacp.tracklength"),
	casu: createDmapTag(readUint, "dacp.su"),
	cavc: createDmapTag(readBool, "dacp.volumecontrollable"),
	cave: createDmapTag(readBool, "dacp.dacpvisualizerenabled"),
	cavs: createDmapTag(readUint, "dacp.visualizer"),
	ceGS: createDmapTag(readStr, "com.apple.itunes.genius-selectable"),
	ceQR: createDmapTag(
		"container",
		"com.apple.itunes.playqueue-contents-response",
	),
	ceSD: createDmapTag(readBplist, "playing metadata"),
	cmcp: createDmapTag("container", "dmcp.controlprompt"),
	cmmk: createDmapTag(readUint, "dmcp.mediakind"),
	cmnm: createDmapTag(readStr, "dacp.devicename"),
	cmpa: createDmapTag("container", "dacp.pairinganswer"),
	cmpg: createDmapTag(readUint, "dacp.pairingguid"),
	cmpr: createDmapTag(readUint, "dmcp.protocolversion"),
	cmsr: createDmapTag(readUint, "dmcp.serverrevision"),
	cmst: createDmapTag("container", "dmcp.playstatus"),
	cmty: createDmapTag(readStr, "dacp.devicetype"),
	mdcl: createDmapTag("container", "dmap.dictionary"),
	miid: createDmapTag(readUint, "dmap.itemid"),
	minm: createDmapTag(readStr, "dmap.itemname"),
	mlcl: createDmapTag("container", "dmap.listing"),
	mlid: createDmapTag(readUint, "dmap.sessionid"),
	mlit: createDmapTag("container", "dmap.listingitem"),
	mlog: createDmapTag("container", "dmap.loginresponse"),
	mpro: createDmapTag(readUint, "dmap.protocolversion"),
	mrco: createDmapTag(readUint, "dmap.returnedcount"),
	msal: createDmapTag(readBool, "dmap.supportsautologout"),
	msbr: createDmapTag(readBool, "dmap.supportsbrowse"),
	msdc: createDmapTag(readUint, "dmap.databasescount"),
	msed: createDmapTag(readBool, "dmap.supportsedit"),
	msex: createDmapTag(readBool, "dmap.supportsextensions"),
	msix: createDmapTag(readBool, "dmap.supportsindex"),
	mslr: createDmapTag(readBool, "dmap.loginrequired"),
	mspi: createDmapTag(readBool, "dmap.supportspersistentids"),
	msqy: createDmapTag(readBool, "dmap.supportsquery"),
	msrv: createDmapTag("container", "dmap.serverinforesponse"),
	mstc: createDmapTag(readUint, "dmap.utctime"),
	mstm: createDmapTag(readUint, "dmap.timeoutinterval"),
	msto: createDmapTag(readUint, "dmap.utcoffset"),
	mstt: createDmapTag(readUint, "dmap.status"),
	msup: createDmapTag(readBool, "dmap.supportsupdate"),
	mtco: createDmapTag(readUint, "dmap.containercount"),
	// Tags with (yet) unknown purpose
	aead: createDmapTag(readBytes, "unknown tag"),
	aeFR: createDmapTag(readUint, "unknown tag"),
	aeSX: createDmapTag(readUint, "unknown tag"),
	asse: createDmapTag(readUint, "unknown tag"),
	atCV: createDmapTag(readUint, "unknown tag"),
	atSV: createDmapTag(readUint, "unknown tag"),
	caks: createDmapTag(readUint, "unknown tag"),
	caov: createDmapTag(readUint, "unknown tag"),
	capl: createDmapTag(readBytes, "unknown tag"),
	casa: createDmapTag(readUint, "unknown tag"),
	casc: createDmapTag(readUint, "unknown tag"),
	cass: createDmapTag(readUint, "unknown tag"),
	ceQA: createDmapTag(readUint, "unknown tag"),
	ceQU: createDmapTag(readBool, "unknown tag"),
	ceMQ: createDmapTag(readBool, "unknown tag"),
	ceNQ: createDmapTag(readUint, "unknown tag"),
	ceNR: createDmapTag(readBytes, "unknown tag"),
	ceQu: createDmapTag(readBool, "unknown tag"),
	cmbe: createDmapTag(readStr, "unknown tag"),
	cmcc: createDmapTag(readStr, "unknown tag"),
	cmce: createDmapTag(readStr, "unknown tag"),
	cmcv: createDmapTag(readIgnore, "unknown tag"),
	cmik: createDmapTag(readUint, "unknown tag"),
	cmsb: createDmapTag(readUint, "unknown tag"),
	cmsc: createDmapTag(readUint, "unknown tag"),
	cmsp: createDmapTag(readUint, "unknown tag"),
	cmsv: createDmapTag(readUint, "unknown tag"),
	cmte: createDmapTag(readStr, "unknown tag"),
	mscu: createDmapTag(readUint, "unknown tag"),
};

export function lookupTag(name: string): DmapTag {
	return _TAGS[name] ?? createDmapTag(readUnknown, "unknown tag");
}
